name: Use Remote Report Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  call-remote-report:
    uses: coder-HDY/test2/.github/workflows/report.yml@main
    with:
      repo_name: ${{ github.repository }}
